# Copyright IBM Corp. 2026
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from pathlib import Path

import pytest

from embasi_qiskit_integration.molecule import geometry

# Methanol from standard internal coordinates: r(C-O)=1.427, r(O-H)=0.956,
# r(C-H)=1.096 A.  Atom order is C, O, hydroxyl H, then the three methyl H.
METHANOL = """6
smiles=CO; charge=0
C     0.000000    0.000000    0.000000
O     1.427000    0.000000    0.000000
H     1.730343    0.906597    0.000000
H     0.374854   -1.029903    0.000000
H     0.374854    0.514952    0.891922
H     0.374854    0.514952   -0.891922
"""


def _write(tmp_path: Path, name: str, text: str) -> Path:
    path = tmp_path / name
    path.write_text(text)
    return path


# --------------------------------------------------------------------------- #
# Parsing
# --------------------------------------------------------------------------- #
def test_parse_atoms_and_metadata(tmp_path: Path):
    """A well-formed file yields one atom line per atom plus the metadata dict."""
    atom_str, metadata = geometry.parse_xyz_atoms_and_metadata(
        _write(tmp_path, "meoh.xyz", METHANOL)
    )

    lines = atom_str.splitlines()
    assert len(lines) == 6
    assert lines[0].split()[0] == "C"
    # Coordinates are normalised to 9 decimal places.
    assert lines[0].split()[1] == "0.000000000"
    assert metadata == {"smiles": "CO", "charge": "0"}


def test_parse_ignores_extra_lines_after_the_atom_block(tmp_path: Path):
    """Trailing content past ``n_atoms`` is not part of the geometry."""
    atom_str, _ = geometry.parse_xyz_atoms_and_metadata(
        _write(tmp_path, "trailing.xyz", METHANOL + "Xx 9.0 9.0 9.0\n")
    )
    assert len(atom_str.splitlines()) == 6


def test_parse_tolerates_a_comment_line_without_metadata(tmp_path: Path):
    """A free-text second line is a comment, not an error: metadata is just empty."""
    text = METHANOL.replace("smiles=CO; charge=0", "methanol, generated by hand")
    _, metadata = geometry.parse_xyz_atoms_and_metadata(_write(tmp_path, "plain.xyz", text))
    assert metadata == {}


@pytest.mark.parametrize(
    ("name", "text", "match"),
    [
        ("empty.xyz", "", "file is empty"),
        ("nan_count.xyz", "six\ncomment\nC 0 0 0\n", "not an atom count"),
        ("short.xyz", "6\ncomment\nC 0.0 0.0 0.0\n", "only"),
        ("missing_col.xyz", "1\ncomment\nC 0.0 0.0\n", "bad atom line"),
        ("nan_coord.xyz", "1\ncomment\nC 0.0 zero 0.0\n", "non-numeric coords"),
    ],
)
def test_parse_rejects_malformed_files(tmp_path: Path, name: str, text: str, match: str):
    """Every malformed shape raises ValueError rather than truncating the molecule."""
    with pytest.raises(ValueError, match=match):
        geometry.parse_xyz_atoms_and_metadata(_write(tmp_path, name, text))


# --------------------------------------------------------------------------- #
# Units
# --------------------------------------------------------------------------- #
def test_split_atom_str_keeps_angstrom(tmp_path: Path):
    """Symbols/positions come straight from the file, in Angstrom.

    Guards the Bohr trap: routing this through a ``Mole`` would return
    ``atom_coords()`` in Bohr and shrink the geometry by ~1.89x.
    """
    atom_str, _ = geometry.parse_xyz_atoms_and_metadata(_write(tmp_path, "meoh.xyz", METHANOL))
    symbols, positions = geometry.split_atom_str(atom_str)

    assert symbols == ["C", "O", "H", "H", "H", "H"]
    assert positions[1] == pytest.approx((1.427, 0.0, 0.0))
    # The hydroxyl O-H bond is 0.956 A; read as Bohr it would come out ~0.51.
    ox, oy, oz = positions[1]
    hx, hy, hz = positions[2]
    bond = ((ox - hx) ** 2 + (oy - hy) ** 2 + (oz - hz) ** 2) ** 0.5
    assert bond == pytest.approx(0.956, abs=1e-3)


# --------------------------------------------------------------------------- #
# Charge precedence
# --------------------------------------------------------------------------- #
def test_charge_without_smiles_uses_metadata():
    """Cases 5 and 6: no SMILES at all -- the ``charge=`` field, else neutral."""
    assert geometry.charge_from_metadata({"charge": "-2"}) == (-2, None)
    assert geometry.charge_from_metadata({"charge": "+3"}) == (3, None)
    assert geometry.charge_from_metadata({}) == (0, None)


def test_unparseable_charge_field_is_ignored(caplog):
    """A typo'd ``charge=`` is warned about and treated as absent, not crashed on."""
    with caplog.at_level("WARNING"):
        assert geometry.charge_from_metadata({"charge": "two"}) == (0, None)
    assert "not a valid integer" in caplog.text


@pytest.mark.parametrize(
    ("smiles", "expected"),
    [("CO", 0), ("[O-]C", -1), ("[NH3+]C", 1), ("[O-]C(=O)C[NH3+]", 0)],
)
def test_charge_from_smiles(smiles: str, expected: int):
    """Case 2: SMILES alone determines the charge (sum of formal charges)."""
    pytest.importorskip("rdkit", reason="needs the 'chem' extra")
    assert geometry.charge_from_metadata({"smiles": smiles}) == (expected, smiles)


def test_charge_agreeing_smiles_and_metadata():
    """Case 1 (agreement): both present and consistent -> that charge."""
    pytest.importorskip("rdkit", reason="needs the 'chem' extra")
    assert geometry.charge_from_metadata({"smiles": "[O-]C", "charge": "-1"}) == (-1, "[O-]C")


def test_contradictory_smiles_and_charge_raises():
    """Case 1 (mismatch): refuse rather than silently pick one.

    The charge fixes ``nelec``, so guessing here would solve a different
    electronic state than the file describes and report it as this molecule's.
    """
    pytest.importorskip("rdkit", reason="needs the 'chem' extra")
    with pytest.raises(ValueError, match="inconsistent"):
        geometry.charge_from_metadata({"smiles": "[NH3+]C", "charge": "0"})


def test_unparseable_smiles_falls_back(caplog):
    """Cases 3 and 4: RDKit rejects the SMILES -> metadata charge, else neutral."""
    pytest.importorskip("rdkit", reason="needs the 'chem' extra")
    bogus = "C1CC"  # unclosed ring: RDKit refuses it
    with caplog.at_level("WARNING"):
        assert geometry.charge_from_metadata({"smiles": bogus, "charge": "-1"}) == (-1, bogus)
        assert geometry.charge_from_metadata({"smiles": bogus}) == (0, bogus)
    assert "could not parse" in caplog.text


def test_charge_without_rdkit_degrades(monkeypatch, caplog):
    """Without rdkit a SMILES cannot be read, so cases 3/4 apply -- but honestly.

    The log must say the cross-check was *skipped*, not that the SMILES failed to
    parse: nothing inspected it, and claiming otherwise would send a user hunting
    a chemistry bug in a valid string.
    """
    monkeypatch.setattr(geometry, "Chem", None)
    monkeypatch.setattr(geometry, "RDLogger", None)

    with caplog.at_level("WARNING"):
        assert geometry.charge_from_metadata({"smiles": "[O-]C", "charge": "-1"}) == (-1, "[O-]C")
        assert geometry.charge_from_metadata({"smiles": "[O-]C"}) == (0, "[O-]C")

    assert "rdkit is not installed" in caplog.text
    assert "could not parse" not in caplog.text


# --------------------------------------------------------------------------- #
# Mole / Atoms construction
# --------------------------------------------------------------------------- #
def test_build_pyscf_mol(tmp_path: Path):
    """The Mole carries the geometry, and PySCF's own max_memory default."""
    atom_str, _ = geometry.parse_xyz_atoms_and_metadata(_write(tmp_path, "meoh.xyz", METHANOL))
    mol = geometry.build_pyscf_mol(atom_str, basis="sto-3g", verbose=0)

    assert mol.natm == 6
    assert mol.nao == 14
    assert mol.nelec == (9, 9)  # neutral methanol: 18 electrons
    assert mol.charge == 0
    # Not the 120 GB the module used to hard-code.
    assert mol.max_memory < 100_000


def test_charge_shifts_electron_count(tmp_path: Path):
    """A net charge must reach the Mole: it is what makes nelec right."""
    atom_str, _ = geometry.parse_xyz_atoms_and_metadata(_write(tmp_path, "meoh.xyz", METHANOL))
    cation = geometry.build_pyscf_mol(atom_str, basis="sto-3g", charge=1, spin=1, verbose=0)
    assert sum(cation.nelec) == 17
    assert cation.charge == 1


def test_read_mol_from_xyz_uses_metadata_charge(tmp_path: Path):
    """The one-shot path derives the charge from the file rather than assuming 0."""
    text = METHANOL.replace("smiles=CO; charge=0", "charge=-1").replace("6\n", "6\n", 1)
    mol = geometry.read_mol_from_xyz(
        _write(tmp_path, "anion.xyz", text), basis="sto-3g", spin=1, verbose=0
    )
    assert mol.charge == -1
    assert sum(mol.nelec) == 19


def test_charge_override_beats_metadata(tmp_path: Path):
    """``charge_override`` wins, for files whose metadata is wrong or missing."""
    mol = geometry.read_mol_from_xyz(
        _write(tmp_path, "meoh.xyz", METHANOL),
        basis="sto-3g",
        charge_override=1,
        spin=1,
        verbose=0,
    )
    assert mol.charge == 1


def test_read_xyz_is_the_shared_front_door(tmp_path: Path):
    """``read_xyz`` resolves geometry + charge once, for every consumer.

    Both readers and ``make_test_data._build_mol`` go through it, so a given file
    can only be read one way -- there is no second charge-resolution path that
    could drift from this one.
    """
    path = _write(tmp_path, "meoh.xyz", METHANOL)
    atom_str, charge, smiles = geometry.read_xyz(path)

    assert len(atom_str.splitlines()) == 6
    assert charge == 0
    assert smiles == "CO"
    # Same atom block the low-level parser produces.
    assert atom_str == geometry.parse_xyz_atoms_and_metadata(path)[0]


def test_read_xyz_override(tmp_path: Path):
    """``charge_override`` short-circuits derivation but keeps the SMILES."""
    text = METHANOL.replace("charge=0", "charge=-1")
    _, charge, smiles = geometry.read_xyz(_write(tmp_path, "anion.xyz", text), charge_override=2)
    assert charge == 2
    assert smiles == "CO"


def test_readers_agree_on_charge(tmp_path: Path):
    """The Mole and Atoms readers cannot disagree, since both delegate to read_xyz."""
    pytest.importorskip("ase", reason="needs the 'embed' extra")
    text = METHANOL.replace("smiles=CO; charge=0", "charge=-1")
    path = _write(tmp_path, "anion.xyz", text)

    mol = geometry.read_mol_from_xyz(path, basis="sto-3g", spin=1, verbose=0)
    _, atoms_charge, _ = geometry.read_atoms_from_xyz(path)
    assert mol.charge == atoms_charge == -1


def test_read_atoms_from_xyz(tmp_path: Path):
    """The ASE bridge returns Atoms in Angstrom plus the derived charge."""
    pytest.importorskip("ase", reason="needs the 'embed' extra")
    atoms, charge, smiles = geometry.read_atoms_from_xyz(_write(tmp_path, "meoh.xyz", METHANOL))

    assert list(atoms.symbols) == ["C", "O", "H", "H", "H", "H"]
    assert atoms.positions[1] == pytest.approx([1.427, 0.0, 0.0])
    assert charge == 0
    assert smiles == "CO"


def test_committed_methanol_fixture_is_readable(data_dir: Path):
    """The committed fixture stays parseable and neutral (used by the workflows)."""
    mol = geometry.read_mol_from_xyz(data_dir / "methanol.xyz", basis="sto-3g", verbose=0)
    assert mol.natm == 6
    assert mol.charge == 0
    assert mol.nelec == (9, 9)
